[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nams"
description = "A helper package for NAMS tutorial"
version = '0.0.1'
readme = "README.rst"
requires-python = ">=3.7"
license = {text = "BSD 3-Clause License"}
